#!/usr/bin/env bash
#etc/passwd history


file="/etc/passwd"


while IFS=":" read -r LREAD user pw uid gid uinfo homedir shell

do

    echo  echo "The user $user is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $pw, \
more info about the user here: $uinfo"

done < "${file}"
