#!/usr/bin/env bash
#etc/passwd history


file="/etc/passwd"


while IFS=: read -r user gid home pw uinfo
do
    echo "The user $user is part of the $gid gang, lives in $home. $uid's place is protected by the passcode $pw, more info about the user here: $uinfo"

done < "${file}"
