#!/usr/bin/env bash
#etc/passwd history


file="/etc/passwd"


while IFS=":" read -r LREAD user gid homdirl uid pw uinfo

do

    echo "The user $user is part of the $gid gang, lives in $homedirl. $uid's place is protected by the passcode $pw, more info about the user here: $uinfo"

done < "${file}"
