#!/usr/bin/env bash
# bad luck, good luck and best School

i=10
while [ $i -gt 0 ];
do

	if [[ $i -eq 7 ]];then
        echo "bad luck"
    elif [[ $i -eq 3 ]];then
        echo "good luck"
        else
		echo "Best School"

        
	fi
i=$((i-1))
done
