#!/usr/bin/env bash
#for ls

#for i in $(ls); do
	#echo $i
	
	#find . -type f | cut -d '/' -f 1 $i 
#done

#for i in $(ls); do echo "$i"; done;

for i in  * ; 
    do
      echo "$i" | cut -f 2 -d "-"
    done
