#!/usr/bin/env bash
#command if, else


con="fin . -name school"
file="school"
if [ $con -eq './school' ]; then
		echo "school file exists"
	else
		echo "school file does not exist" 
	
	else [ -s $file ]; then
		echo "school file is not empty"
	fi
		
	else
		echo "school file is empty"
		
	fi

	else [ $file ]; then
                echo "school is a regular file"

        fi


		
fi






