#!/usr/bin/env bash
# to infinity and beyond 


filepid="/var/run/my_process.pid"

start() {
	# inicia el proceso manage_my_process, crea el archivo myprocess.pid que contiene el PID del proceso 
	./manage_my_process &
	echo "$!" > "$filepid"
}

stop() {
	
	#mata el proceso y elimina el archivo my process
	sudo pkill -f manage_my_process && rm "$filepid"
}



case "$1" in 
	
start ) start	
       	echo "manage_my_process started"
	 ;;

 stop ) stop
	 echo "manage_my_process stopped"
	;;
	

restart ) stop; start 
	echo "manage_my_process restarted"
	;;

*) echo "Usage: manage_my_process {start|stop|restart}"
 	

esac
